# Generated by Django 6.0.7 on 2026-07-15 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_locations', '0001_initial'),
        ('app_tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publish_config', to='app_locations.location')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_tours', to=settings.AUTH_USER_MODEL)),
                ('published_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_configs', to='app_tours.tourversion')),
            ],
        ),
        migrations.CreateModel(
            name='WhitelistDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publish_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_domains', to='app_publishing.publishconfig')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('publish_config', 'domain'), name='unique_domain_per_publish_config')],
            },
        ),
    ]
