# Generated by Django 6.0.7 on 2026-07-15 03:29

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_locations', '0002_alter_location_managers_and_more'),
        ('app_publishing', '0001_initial'),
        ('app_tours', '0002_alter_tourversion_managers_tourversion_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publishconfig',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='whitelistdomain',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='whitelistdomain',
            name='unique_domain_per_publish_config',
        ),
        migrations.AddField(
            model_name='publishconfig',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='publishconfig',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='whitelistdomain',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='whitelistdomain',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='publishconfig',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_configs', to='app_locations.location'),
        ),
        migrations.AddConstraint(
            model_name='publishconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('location',), name='unique_active_publish_config_per_location'),
        ),
        migrations.AddConstraint(
            model_name='whitelistdomain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('publish_config', 'domain'), name='unique_active_domain_per_publish_config'),
        ),
    ]
