# Generated by Django 6.0.7 on 2026-07-15 03:29

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_locations', '0001_initial'),
        ('app_projects', '0002_alter_project_managers_project_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location_slug_per_project',
        ),
        migrations.AddField(
            model_name='location',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'slug'), name='unique_active_location_slug_per_project'),
        ),
    ]
