# Generated by Django 6.0.7 on 2026-07-15 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_key', models.CharField(max_length=100)),
                ('original_file', models.ImageField(upload_to='scenes/originals/')),
                ('original_width', models.PositiveIntegerField(blank=True, null=True)),
                ('original_height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('tile_base_path', models.CharField(blank=True, max_length=500)),
                ('max_zoom_level', models.PositiveSmallIntegerField(default=3)),
                ('tile_size', models.PositiveSmallIntegerField(default=512)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_assets', to='app_tours.tourversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tour_version', 'scene_key'), name='unique_scene_key_per_tour_version')],
            },
        ),
    ]
