# Generated by Django 6.0.7 on 2026-07-15 03:29

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0001_initial'),
        ('app_tours', '0002_alter_tourversion_managers_tourversion_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sceneasset',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='sceneasset',
            name='unique_scene_key_per_tour_version',
        ),
        migrations.AddField(
            model_name='sceneasset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sceneasset',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name='sceneasset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tour_version', 'scene_key'), name='unique_active_scene_key_per_tour_version'),
        ),
    ]
