# Generated by Django 6.0.7 on 2026-07-15 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_publishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('country_breakdown', models.JSONField(blank=True, default=dict)),
                ('device_breakdown', models.JSONField(blank=True, default=dict)),
                ('referrer_breakdown', models.JSONField(blank=True, default=dict)),
                ('publish_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='app_publishing.publishconfig')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('publish_config', 'date'), name='unique_daily_stat_per_publish_config')],
            },
        ),
        migrations.CreateModel(
            name='TourVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('other', 'Other')], default='other', max_length=10)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('referrer_domain', models.CharField(blank=True, max_length=255)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('publish_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='app_publishing.publishconfig')),
            ],
            options={
                'indexes': [models.Index(fields=['publish_config', 'visited_at'], name='app_analyti_publish_3630a6_idx'), models.Index(fields=['publish_config', 'country_code'], name='app_analyti_publish_3a3d51_idx'), models.Index(fields=['publish_config', 'device_type'], name='app_analyti_publish_19ae66_idx'), models.Index(fields=['publish_config', 'referrer_domain'], name='app_analyti_publish_de2b4d_idx')],
            },
        ),
    ]
