# Generated by Django 6.0.7 on 2026-07-15 03:29

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_analytics', '0001_initial'),
        ('app_publishing', '0002_alter_publishconfig_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dailystat',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tourvisit',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='dailystat',
            name='unique_daily_stat_per_publish_config',
        ),
        migrations.AddField(
            model_name='dailystat',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dailystat',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='tourvisit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tourvisit',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name='dailystat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('publish_config', 'date'), name='unique_active_daily_stat_per_publish_config'),
        ),
    ]
