# Generated by Django 6.0.7 on 2026-07-15 02:39

import app_tours.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(editable=False)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(validators=[app_tours.models.validate_tour_data])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='tours/thumbnails/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('changelog', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tour_versions', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app_locations.location')),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['location', 'status'], name='app_tours_t_locatio_651203_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'version_number'), name='unique_tour_version_per_location')],
            },
        ),
    ]
